##
 # @Author Rizki Mufrizal <mufrizalrizki@gmail.com>
 # @Since Apr 30, 2016
 # @Time 10:25:28 PM
 # @Encoding ISO-8859-1
 # @Project Pelayanan-LabTI
 # @Package Expression package is undefined on line 7, column 15 in Templates/Other/yml.properties.
 #
 ##
 
spring:
    profiles:
        active: development
        
    # spring datasource jpa
    datasource: 
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:pelayanan;DB_CLOSE_DELAY=-1
        username: administrator
        password: administratorlabti2016
        poolName: SpringBootHikariCP
        maximumPoolSize: 5
        minimumIdle: 3
        maxLifetime: 2000000
        connectionTimeout: 30000
        idleTimeout: 30000
    
    # spring hibernate    
    jpa: 
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: update
        properties: 
            hibernate: 
                format_sql: true
        database-platform: org.hibernate.dialect.H2Dialect

    # jackson config
    jackson: 
        serialization: 
            indent_output: true

    # spring devtools
    devtools: 
        livereload: 
            enabled: true

    # spring thymeleaf
    thymeleaf: 
        cache: false
